bash harder

diff --git a/.github/actions/fetch-artifact/action.yml b/.github/actions/fetch-artifact/action.yml
--- a/.github/actions/fetch-artifact/action.yml
+++ b/.github/actions/fetch-artifact/action.yml
@@ -46,13 +46,13 @@ runs:
       shell: bash
       run: | # bash
         if [ -e "metabase.jar" ]; then
-          echo "metabase.jar is already in the right place"
-        else if [ -e "target/uberjar/metabase.jar" ]; then
-          # Move the file to the destination directory
-          mv target/uberjar/metabase.jar metabase.jar
+            echo "metabase.jar is already in the right place"
+        elif [ -e "target/uberjar/metabase.jar" ]; then
+            # Move the file to the destination directory
+            mv target/uberjar/metabase.jar metabase.jar
         else
-          echo "Could not find the metabase.jar file"
-          exit 1
+            echo "Could not find the metabase.jar file"
+            exit 1
         fi
 
     - name: Verify that this is a valid JAR file
