test build

diff --git a/.github/workflows/build-for-release.yml b/.github/workflows/build-for-release.yml
--- a/.github/workflows/build-for-release.yml
+++ b/.github/workflows/build-for-release.yml
@@ -77,28 +77,27 @@ jobs:
     - name: Check out the code to verify the release branch
       uses: actions/checkout@v3
       with:
-        fetch-depth: 0  # IMPORTANT! to get all the branches
-    - name: Ensure that the specified commit exists in a release branch
-      env:
-        COMMIT: ${{ inputs.commit }}
+        fetch-depth: 0
+        sparse-checkout: release
+    - name: Prepare build scripts
+      run: cd ${{ github.workspace }}/release && yarn && yarn build
+    - name: Get Release Branch
+      uses: actions/github-script@v6
+      id: release_branch
+      with:
+        result_encoding: string
+        script: | # js
+          const { getReleaseBranch } = require('${{ github.workspace }}/release/dist/index.cjs');
+          const version = '${{ inputs.version }}';
+          const releaseBranch = getReleaseBranch(version);
+          return releaseBranch;
+    - name: Ensure that the specified commit exists in the ${{ steps.release_branch.outputs.result }} release branch
       run: |
-        echo "Checking if the specified commit is in a release branch..."
-
-        git branch -a --contains $COMMIT > branches.txt
-        if [[ $(grep -c master branches.txt) =~ 1 ]]; then
-          echo "Found in master branch. ABORT!"
-          exit -1
-        fi
-        if [[ $(grep -c 'release-x' branches.txt) =~ 1 ]]; then
-          echo "Found the commit $COMMIT in:"
-          git branch -a --contains $COMMIT
-          echo "Proceeding to the next step..."
-          exit 0
-        else
-          echo "Commit $COMMIT is not found in a single release branch"
-          echo "ABORT!."
-          exit -1
-        fi
+        RELEASE_BRANCH=${{ steps.release_branch.outputs.result }}
+        git checkout $RELEASE_BRANCH
+        git branch --contains ${{ inputs.commit }} | grep -q $RELEASE_BRANCH \
+          && echo "Commit found in correct release branch" \
+          || (echo "Commit not found in correct release branch" && exit 1)
 
   get-build-requirements:
     runs-on: ubuntu-22.04
@@ -113,7 +112,7 @@ jobs:
         sparse-checkout: release
     - name: Prepare build scripts
       run: cd ${{ github.workspace }}/release && yarn && yarn build
-    - name: Get Release Version
+    - name: Get build dependencies
       uses: actions/github-script@v6
       id: dependencies
       with:
@@ -123,9 +122,7 @@ jobs:
           const version = '${{ inputs.version }}';
 
           const requirements = getBuildRequirements(version);
-
           const build_process = getMajorVersion(version) < 46 ? 'legacy' : 'new';
-
           console.log('Build process:', build_process);
 
           return {
@@ -153,7 +150,6 @@ jobs:
         fi
 
         echo "VERSION=$version" >> $GITHUB_ENV
-
     - name: Setup Java ${{ needs.get-build-requirements.outputs.java_version }}
       uses: actions/setup-java@v3
       with:
