release from trigger

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,59 +1,133 @@
 name: Release [WIP]
 
 on:
-  push:
-    tags:
-    - 'v*'
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'Metabase version (e.g. v0.46.3)'
+        type: string
+        required: true
+      commit:
+        description: 'A full-length commit SHA-1 hash'
+        required: true
 
 jobs:
-
-  trigger-docs-update:
+  download-uberjar-artifact:
     runs-on: ubuntu-22.04
     timeout-minutes: 10
+    strategy:
+      matrix:
+        edition: [oss, ee]
     steps:
-      - uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.DOCS_UPDATE_TOKEN }}
-          script: |
-            github.rest.repos.createDispatchEvent({
-              owner: '${{ github.repository_owner }}',
-              repo: '${{ secrets.DOCS_REPO }}',
-              event_type: 'trigger-docs-update',
-              client_payload: {
-                version: '${{ github.ref_name }}'
-              }
-            });
-
-  download-uberjar:
-    runs-on: ubuntu-22.04
-    timeout-minutes: 10
-    steps:
-    - name: Download Uberjar for ${{ github.ref_name }}
+    - name: Fail early on the incorrect version format
+      if: ${{ !(startsWith(inputs.version,'v0.') || startsWith(inputs.version,'v1.')) }}
       run: |
-        JAR_DOWNLOAD_URL=https://downloads.metabase.com/${{ github.ref_name }}/metabase.jar
-        if [[ ${{ github.ref_name }} == v1* ]]; then
-          JAR_DOWNLOAD_URL=https://downloads.metabase.com/enterprise/${{ github.ref_name }}/metabase.jar
-        fi
-        echo $JAR_DOWNLOAD_URL > url.txt
-        echo "----- Downloading Uberjar from $JAR_DOWNLOAD_URL -----"
-        curl -OL $JAR_DOWNLOAD_URL
-        stat ./metabase.jar
-        date | tee timestamp
+        echo "The version format is invalid!"
+        echo "It must start with either 'v0.' or 'v1.'."
+        echo "Please, try again."
+        exit 1
+    - name: find_release_artifact
+      uses: actions/github-script@v6
+      with:
+        result-encoding: string
+        script: |
+          const artifacts = await github.rest.actions.listArtifactsForRepo({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            name: `metabase-${{ matrix.edition }}-${{ inputs.commit }}-uberjar`,
+            per_page: 1,
+          });
+
+          if (!artifacts.data?.artifacts?.[0]?.archive_download_url) {
+            throw new Error(`No artifacts found for ${inputs.commit}`);
+          }
+
+          return artifacts.data.artifacts[0].archive_download_url;
+    - name: download-uberjar-artifact
+      run: |
+        DOWNLOAD_LINK="$(echo ${{ steps.find_release_artifact.outputs.result }})"
+
+        curl -sL \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            $DOWNLOAD_LINK \
+            -o mb.zip
+    - run: |
+        unzip mb.zip
     - name: Verify that this is a valid JAR file
       run: file --mime-type ./metabase.jar | grep "application/zip"
-    - name: Reveal its version.properties
-      run: jar xf metabase.jar version.properties && cat version.properties
-    - name: Calculate SHA256 checksum
-      run: sha256sum ./metabase.jar | tee SHA256.sum
+    - name: verify_checksum
+      run: |
+        grep -q $(sha256sum ./metabase.jar) SHA256.sum && echo "checksums match" || exit 1
     - name: Upload Uberjar as artifact
       uses: actions/upload-artifact@v3
       with:
-        name: metabase-uberjar-${{ github.ref_name }}
+        name: metabase-${{ matrix.edition }}-uberjar
         path: |
           ./metabase.jar
-          ./url.txt
-          ./timestamp
+          ./COMMIT-ID
           ./SHA256.sum
+
+  push-tags:
+    runs-on: ubuntu-22.04
+    timeout-minutes: 10
+    strategy:
+      matrix:
+        edition: [oss, ee]
+    steps:
+    # EE is always v1.x.y, OSS is always v0.x.y
+    - name: Determine the canonical version
+      uses: actions/github-script@v6
+      id: canonical_version
+      with:
+        result-encoding: string
+        script: |
+          const version = '${{ inputs.version }}';
+          const edition = '${{ matrix.edition }}';
+
+          const canonical_version = edition === "ee"
+            ? version.replace(/^v0\./, "v1."); // always e.g. v1.47.2
+            : version.replace(/^v1\./, "v0."); // always e.g. v0.47.2
+
+          console.log("The canonical version of this Metabase", edition, "edition is", canonical_version);
+
+          // delete old ref
+          await github.rest.git.deleteRef({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            ref: `refs/tags/${canonical_version}`,
+          });
+
+          // create new ref
+          const newRef = await github.rest.git.createRef({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            ref: `refs/tags/${canonical_version}`,
+            sha: '${{ inputs.commit }}',
+          });
+
+          if (newRef.status !== 201) {
+            console.error(`failed to tag release`);
+            process.exit(1);
+          }
+
+  # trigger-docs-update:
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 10
+  #   steps:
+  #     - uses: actions/github-script@v6
+  #       with:
+  #         github-token: ${{ secrets.DOCS_UPDATE_TOKEN }}
+  #         script: |
+  #           github.rest.repos.createDispatchEvent({
+  #             owner: '${{ github.repository_owner }}',
+  #             repo: '${{ secrets.DOCS_REPO }}',
+  #             event_type: 'trigger-docs-update',
+  #             client_payload: {
+  #               version: '${{ github.ref_name }}'
+  #             }
+  #           });
 
   check-uberjar:
     runs-on: ubuntu-22.04
@@ -88,6 +162,45 @@ jobs:
       timeout-minutes: 3
     - name: Check API health
       run: curl -s localhost:3000/api/health
+
+  upload-to-s3:
+    runs-on: ubuntu-22.04
+    needs: check-uberjar
+    timeout-minutes: 15
+    strategy:
+      matrix:
+        edition: [oss, ee]
+    steps:
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_S3_RELEASE_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_S3_RELEASE_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+    - uses: actions/download-artifact@v3
+      name: Retrieve uberjar artifact
+      with:
+        name: metabase-${{ matrix.edition }}-uberjar
+    - name: Determine the upload path ## EE is always v1.x.y, OSS is always v0.x.y
+      uses: actions/github-script@v6
+      id: version_path
+      with:
+        result-encoding: string
+        script: |
+          const version = '${{ inputs.version }}';
+          const edition = '${{ matrix.edition }}';
+
+          const version_path = edition === 'ee'
+            ? 'enterprise/' + version.replace(/^v0\./, "v1."); // always e.g. v1.47.2
+            : version.replace(/^v1\./, "v0."); // always e.g. v0.45.6;
+
+          console.log("The download path for this", edition, "edition is", version_path);
+          return version_path;
+    - name: Upload to S3
+      run:
+        # FIXME: test bucket
+        aws s3 cp ./target/uberjar/metabase.jar s3://iethree-downloads.metabase.com/${{ steps.version_path.outputs.result }}/metabase.jar
+
 
   containerize:
     runs-on: ubuntu-22.04
@@ -267,21 +380,21 @@ jobs:
       run: while ! curl -s 'http://localhost:3000/api/health' | grep '{"status":"ok"}'; do sleep 1; done
       timeout-minutes: 3
 
-  publish-elastic-beanstalk-artifacts:
-    runs-on: ubuntu-22.04
-    needs: containerize
-    timeout-minutes: 15
-    env:
-      NO_SLACK: 1
-    steps:
-    - uses: actions/checkout@v3
-    - name: Prepare back-end environment
-      uses: ./.github/actions/prepare-backend
-    - name: Configure AWS credentials for S3
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_S3_RELEASE_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_S3_RELEASE_SECRET_ACCESS_KEY }}
-        aws-region: us-east-1
-    - name: Publish Elastic Beanstalk artifacts
-      run: ./bin/ebs.sh :version ${{ github.ref_name }}
+  # publish-elastic-beanstalk-artifacts:
+  #   runs-on: ubuntu-22.04
+  #   needs: containerize
+  #   timeout-minutes: 15
+  #   env:
+  #     NO_SLACK: 1
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - name: Prepare back-end environment
+  #     uses: ./.github/actions/prepare-backend
+  #   - name: Configure AWS credentials for S3
+  #     uses: aws-actions/configure-aws-credentials@v1
+  #     with:
+  #       aws-access-key-id: ${{ secrets.AWS_S3_RELEASE_ACCESS_KEY_ID }}
+  #       aws-secret-access-key: ${{ secrets.AWS_S3_RELEASE_SECRET_ACCESS_KEY }}
+  #       aws-region: us-east-1
+  #   - name: Publish Elastic Beanstalk artifacts
+  #     run: ./bin/ebs.sh :version ${{ github.ref_name }}
